# Generated by Django 5.1.4 on 2025-01-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todoitem_status'),
        ('todo_app', '0004_reset_todoitem_id_sequence'),
    ]

    operations = [
    ]
